---
version: "2.1"
services:
  commune:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: commune
    shm_size: '1gb' # for the shared memory size
    volumes:
      - ~/.commune:/config/.commune
      - ~/.commune:/root/.commune
      - ./:/commune
      - /var/run/docker.sock:/var/run/docker.sock #Nuclear option
    ports:
      - 50050-50250:50050-50250
      # - 8501-8511:8501-8511

    restart: unless-stopped