[tool.poetry]
name = "commune"
version = "0.1.0"
description = ""
authors = ["tommiful <tommiful999@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
setuptools = "^69.1.1"
uvicorn = "^0.27.1"
fastapi = "^0.110.0"
substrate-interface = "^1.7.7"
torch = "^2.2.1"
safetensors = "^0.4.2"
streamlit = "^1.31.1"
plotly = "^5.19.0"
gradio = "^4.20.1"
sse-starlette = "^2.0.0"
msgpack-numpy = "^0.4.8"
retry = "^0.9.2"
psutil = "^5.9.8"
munch = "^4.0.0"
grpcio = "^1.62.0"
grpcio-tools = "^1.62.0"
scipy = "^1.12.0"
loguru = "^0.7.2"
rich = "^13.7.1"
aiofiles = "^23.2.1"
aiohttp = "^3.9.3"
nest-asyncio = "^1.6.0"
openai = "^1.13.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
